require("plugins")
require("lion.core.color")
require("lion.core.keymaps")
require("lion.core.options")
require("lion.plugin.tree")
require("lion.plugin.lualine")
require("lion.plugin.nvim-cmp")
require("lion.plugin.lsp.mason")
